#!/bin/sh

uci -q batch <<'EOF'
delete network.lan
set network.lan='interface'
set network.lan.device='br-lan'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.1'
set network.lan.netmask='255.255.255.0'

delete network.wan
set network.wan='interface'
set network.wan.device='eth1'
set network.wan.proto='dhcp'
EOF

uci -q batch <<'EOF'
delete dhcp.lan
set dhcp.lan='dhcp'
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
EOF

uci -q get network.@globals[0] >/dev/null ||
	uci -q add network globals >/dev/null
uci -q set network.@globals[0].packet_steering='1'

uci commit network
uci commit dhcp
exit 0
